// layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TheHeader from "./TheHeader";
import TheFooter from "./TheFooter"; // Correct import
import { ReduxProvider } from "./store/provider";
import { Providers } from "./components/Providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="w-full max-container">
      <body className={inter.className}>
        <ReduxProvider>
          <Providers>
            <div className="xl:padding-l wide:padding-r padding-b">
              <TheHeader />
            </div>
            {children}
            <div className="mt-[200px] xl:padding-l wide:padding-r padding-b">
              <TheFooter />
            </div>
          </Providers>
        </ReduxProvider>
      </body>
    </html>
  );
}
